import React from "react";
import Navbar from "../../components/navbar/Navbar";
import Header from "../../components/header/Header";
import MailList from "../../components/mailList/MailList";
import Footer from "../../components/footer/Footer";
import BookingItem from "../../components/BookingItem/BookingItem";
const Bookings = () => {
  let bookings = [
    {
      _id: "65df9e90d1edf62697139baf",
      name: "Hilton Alexandria Corniche",
      type: "hotel",
      city: "alex",
      country: "egypt",
      address: ["\n544 El Geish Road , Sidi Bishr, 21611 Alexandria, Egypt\n"],
      distance: 32,
      photos: [
        "https://cf.bstatic.com/xdata/images/hotel/max300/490791170.jpg?k=1c6559bb207569f3cb8546fd886aafbee8484ca55b3181459492ad71c67a002d&o=&hp=1",
        "https://cf.bstatic.com/xdata/images/hotel/max300/490791169.jpg?k=bd2d80106b2224358295a30d5de90c1b1f1ba62ec7db695d1f996043f8edca15&o=&hp=1",
        "https://cf.bstatic.com/xdata/images/hotel/max300/490791191.jpg?k=0729d926f7a3d70c480a474bdf912ecc4c15cad5217c0210e1f3a6fb6c3e453b&o=&hp=1",
        "https://cf.bstatic.com/xdata/images/hotel/max300/490791179.jpg?k=75825a2d5178d82174273a85bdd26de433c324f988b6873ff4018a8fb98b849e&o=&hp=1",
        "https://cf.bstatic.com/xdata/images/hotel/max500/483726259.jpg?k=21c328b4eb2f4d04c5f584a3881957633cb9daff91bef78a1265aefc24285aa3&o=&hp=1",
        "https://cf.bstatic.com/xdata/images/hotel/max500/490791174.jpg?k=02898bbfa935a122c9816e09ebc1b0bc394b350ef4660cf659c5278247ccb37c&o=&hp=1",
        "https://cf.bstatic.com/xdata/images/hotel/max1024x768/504400856.jpg?k=0017eebdb5b09533a13c768bc0b8ed5509440c2cd1639a50f3dc0801c5bc958b&o=&hp=1",
      ],
      desc: "Boasting an ideal location in the heart of Alexandria, Hilton Alexandria Corniche features its own private beach and wellness facility. Guests can enjoy sea views from the panoramic pool terrace or indulge in various cuisines available at the 6 outlets.\n\nAll accommodations feature elegant and modern décor with free standard WIFI with speed up to 4MB. Each room is equipped with a flat-screen TV, a wardrobe and an electric kettle. Some includes a balcony or terrace with sea view. The suite comes with a living room.\n\nGuests can start the day with a breakfast or nutritious light bite; savor innovative dishes prepared with only the freshest ingredients from Greek, Lebanese, French, Asian to Middle Eastern cuisine, or simply relax with a cup of coffee in the hotel lounge.\n\nAfter an energizing workout at the fully equipped gym, guests have various options for relaxation such as massage treatments or hot tub, all at an added fee. For kids, the hotel offers a children’s playground in the summer by the beach.\n\nA number of restaurants, casinos and markets are situated on the Corniche, the 15 km of beachfront promenade. Al Nozha Alexandria Airport is 12 km away. A complimentary beach shuttle service is available.",
      rating: 5,
      rooms: [
        "65df9e8ad1edf62697139b9f",
        "65df9e8dd1edf62697139ba0",
        "65df9e8dd1edf62697139ba1",
        "65df9e8dd1edf62697139ba2",
        "65df9e8ed1edf62697139ba3",
        "65df9e8ed1edf62697139ba4",
        "65df9e8ed1edf62697139ba5",
        "65df9e8fd1edf62697139ba6",
        "65df9e8fd1edf62697139ba7",
        "65df9e8fd1edf62697139ba8",
        "65df9e8fd1edf62697139ba9",
        "65df9e90d1edf62697139baa",
        "65df9e90d1edf62697139bab",
        "65df9e90d1edf62697139bac",
        "65df9e90d1edf62697139bad",
        "65df9e90d1edf62697139bae",
      ],
      cheapestPrice: 702,
      featured: true,
      aminity: [
        "Outdoor swimming pool",
        "Beachfront",
        "Free WiFi",
        "Private parking",
        "Family rooms",
        "Airport shuttle",
        "Tea/coffee maker in all rooms",
        "Bar",
        "Private beach area",
        "Very good breakfast",
        "Outdoor swimming pool",
        "Beachfront",
        "Free WiFi",
        "Private parking",
        "Family rooms",
        "Airport shuttle",
        "Tea/coffee maker in all rooms",
        "Bar",
        "Private beach area",
        "Very good breakfast",
        "Toilet paper",
        "Towels",
        "Bath or shower",
        "Private bathroom",
        "Toilet",
        "Free toiletries",
        "Hairdryer",
        "Bath",
        "Shower",
        "Linen",
        "Wardrobe or closet",
        "Alarm clock",
        "Beachfront",
        "Sun terrace",
        "Private beach area",
        "BBQ facilities",
        "Balcony",
        "Terrace",
        "Tumble dryer",
        "Electric kettle",
        "Fold-up bed",
        "Live sport events (broadcast)",
        "Live music/performance",
        "Happy hour",
        "Themed dinner nights",
        "Beach",
        "Evening entertainment",
        "Water sport facilities on site",
        "Nightclub/DJ",
        "Entertainment staff",
        "Darts",
        "Karaoke",
        "Children's playground",
        "Desk",
        "Flat-screen TV",
        "Satellite channels",
        "Radio",
        "Telephone",
        "TV",
        "Coffee house on site",
        "Fruits",
        "Wine/champagne",
        "Kid meals",
        "Special diet menus (on request)",
        "Breakfast in the room",
        "Bar",
        "Minibar",
        "Restaurant",
        "Tea/Coffee maker",
        "Valet parking",
        "Parking garage",
        "Invoice provided",
        "Lockers",
        "Concierge service",
        "ATM/cash machine on site",
        "Luggage storage",
        "Tour desk",
        "Currency exchange",
        "24-hour front desk",
        "Kids' outdoor play equipment",
        "Babysitting/child services",
        "Daily housekeeping",
        "Trouser press",
        "Ironing service",
        "Dry cleaning",
        "Laundry",
        "Fax/photocopying",
        "Meeting/banquet facilities",
        "Fire extinguishers",
        "CCTV outside property",
        "CCTV in common areas",
        "Smoke alarms",
        "Security alarm",
        "Key card access",
        "24-hour security",
        "Safety deposit box",
        "Shuttle service",
        "Shared lounge/TV area",
        "Hypoallergenic",
        "Designated smoking area",
        "Air conditioning",
        "Allergy-free room",
        "Wake-up service",
        "Tile/marble floor",
        "Car hire",
        "Laptop safe",
        "Lift",
        "Heating",
        "Family rooms",
        "Barber/beauty shop",
        "Ironing facilities",
        "Facilities for disabled guests",
        "Airport shuttle",
        "Non-smoking rooms",
        "Iron",
        "Wake up service/Alarm clock",
        "Room service",
        "Toilet with grab rails",
        "Wheelchair accessible",
        "Entire unit wheelchair accessible",
        "Upper floors accessible by elevator",
        "Open all year",
        "All ages welcome",
        "Infinity pool",
        "Pool/beach towels",
        "Pool bar",
        "Sun umbrellas",
        "Fence around pool",
        "Kids' pool",
        "Fitness/spa locker rooms",
        "Personal trainer",
        "Fitness",
        "Massage chair",
        "Spa/wellness packages",
        "Spa lounge/relaxation area",
        "Steam room",
        "Spa facilities",
        "Body scrub",
        "Body treatments",
        "Waxing services",
        "Facial treatments",
        "Beauty Services",
        "Sun umbrellas",
        "Sun loungers or beach chairs",
        "Hot tub/Jacuzzi",
        "Massage",
        "Spa and wellness centre",
        "Sauna",
        "Arabic",
        "English",
      ],
      numberOfReviewers: 1,
      numberOfStars: 2,
      score: 7.594575267479124,
      numRatings: 1,
      reviewScore: "Wonderful",
      recommendation: [
        "65df9ec1d1edf62697139d0f",
        "65df9f67d1edf6269713a1c6",
        "65df9f55d1edf6269713a142",
        "65df9ee7d1edf62697139e1d",
        "65df9ea9d1edf62697139c66",
        "65df9eb1d1edf62697139c9f",
        "65df9eb5d1edf62697139cb9",
        "65e21083fca7967f42b4df75",
        "65df9e91d1edf62697139bb6",
        "65df9e94d1edf62697139bc6",
      ],
      ownerId: "65bea8893e200fba6078f5d8",
    },
  ];
  return (
    <div>
      <Navbar />
      <Header type="list" />
      <div className="ListPropertyContainer">
        <div className="innerContainer">
          {bookings.map((item) => {
            return <BookingItem key={item._id} item={item} />;
          })}
        </div>
      </div>
      <MailList />
      <Footer />
    </div>
  );
};

export default Bookings;
