name: hotelyn
description: "Awesome Flutter project"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  go_router: ">=12.1.3 <14.0.0"
  email_validator: '^2.1.16'
  toast: ^0.3.0
  shared_preferences: ^2.0.15
  dio: ^5.4.3
  conditional_builder_null_safety: ^0.0.6
  csc_picker: ^0.2.7
  intl: ^0.17.0
  comment_box: ^0.0.18
  geocoding: ^2.0.5
  get: ^4.6.5
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <4.0.0"
  melos: ">=3.1.1 <5.0.0"
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0+1

fonts:
  - family: DMSans
    fonts:
      - asset: assets/fonts/DMSans_18pt-Regular.ttf
        style: regular
      - asset: assets/fonts/DMSans_18pt-Medium.ttf
        style: medium
      - asset: assets/fonts/DMSans_18pt-Bold.ttf
        style: bold

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hotelyn/
    - assets/images/onboarding/
    - assets/images/messages/
    - assets/icons/
    - assets/languages/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans_18pt-Regular.ttf
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans_18pt-Bold.ttf
          weight: 700
